spring.application.name=task-manager-back

spring.datasource.url=jdbc:postgresql://localhost:5434/taskmanager_db
spring.datasource.username=christian
spring.datasource.password=secret123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect