version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taskmanager-postgres
    restart: always
    ports:
      - "5434:5432"  # Puerto externo 5434 para evitar conflictos
    environment:
      POSTGRES_DB: taskmanager_db
      POSTGRES_USER: christian
      POSTGRES_PASSWORD: secret123
    volumes:
      - taskmanager-data:/var/lib/postgresql/data

volumes:
  taskmanager-data: